return {
  ["workshop-1207269058"]={
    configuration_options={
      ddon=true,
      hbcolor="dynamic",
      hblength=5,
      hbpos=1,
      hbstyle="heart",
      value=true
    },
    enabled=true
  },
  ["workshop-1234341720"]={
    configuration_options={
      battleaxe="normal",
      book_dogs="normal",
      book_freeze="normal",
      book_healing="normal",
      book_lava="normal",
      book_light="normal",
      book_meteor="normal",
      book_sleepingfield="normal",
      book_slowness="normal",
      book_summon="normal",
      book_tornado="normal",
      deathscythe="normal",
      flamesword="normal",
      halberd="normal",
      healingstaff="normal",
      katana="normal",
      pirate="normal",
      poseidon="normal",
      purplesword="normal",
      skullspear="normal",
      teleportstaff="normal"
    },
    enabled=true
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2
    },
    enabled=true
  },
  ["workshop-378965501"]={
    configuration_options={ MARBLESUITSPDMULT=1, PIGGYBACKSPDMULT=1 },
    enabled=true
  },
  ["workshop-441356490"]={
    configuration_options={
      AMULET_DURABILITY=2,
      ARMOR_DURABILITY=2,
      BOOK_DURABILITY=2,
      CAMPING_DURABILITY=2,
      CLOTHING_DURABILITY=2,
      DEBUGOPTIONS="Off",
      FOOD_PRESERVATION=2,
      FOOD_SELECTION="All",
      GOLD_DURABILITY=2,
      LIGHT_DURABILITY=2,
      STAFF_DURABILITY=2,
      TOOL_DURABILITY=2,
      TRAP_DURABILITY=2,
      WEAPON_DURABILITY=2
    },
    enabled=true
  },
  ["workshop-462434129"]={
    configuration_options={
      MOD_RESTART_ALLOW_KILL=true,
      MOD_RESTART_ALLOW_RESTART=true,
      MOD_RESTART_ALLOW_RESURRECT=true,
      MOD_RESTART_CD_BONUS=0,
      MOD_RESTART_CD_KILL=0,
      MOD_RESTART_CD_MAX=0,
      MOD_RESTART_CD_RESTART=0,
      MOD_RESTART_CD_RESURRECT=0,
      MOD_RESTART_FORCE_DROP_MODE=0,
      MOD_RESTART_IGNORING_ADMIN=true,
      MOD_RESTART_MAP_SAVE=2,
      MOD_RESTART_RESURRECT_HEALTH=0,
      MOD_RESTART_TRIGGER_MODE=1,
      MOD_RESTART_WELCOME_TIPS=true,
      MOD_RESTART_WELCOME_TIPS_TIME=6
    },
    enabled=true
  },
  ["workshop-463718554"]={
    configuration_options={
      AMOUNTOFCHESTERS=8,
      BEESSPEEDMULTIPLIER=1.2,
      CANHAUNT=1,
      CAVESTARTINGITEMS=true,
      DRAGONFLYBALANCE=true,
      DRYINGSPEEDMULTIPLIER=2,
      EMPTYINVENTORYDAYS=-1,
      FARMINGSPEEDMULTIPLIER=2,
      GHOSTSANITYDRAIN=false,
      KRAMPUSMULTIPLIER=2,
      MAXMAXPLAYERS=32,
      NIGHTSTARTINGITEMS=true,
      PREVENTBURNING=0,
      PREVENTDESTROYINGDAYS=2,
      PREVENTSTEALINGDAYS=0,
      PVPSTARTINGITEMS=true,
      RENEWLIMITEDRESOURCES=18,
      RESIZEFIREPITS=true,
      REVEALMAP=1,
      REVIVERCRAFTPENALTY=false,
      SEASONSTARTINGITEMS=true,
      SPREADFIRE=2,
      STARTINGITEMS=true
    },
    enabled=true
  },
  ["workshop-501385076"]={ configuration_options={  }, enabled=true },
  ["workshop-544126369"]={
    configuration_options={
      beefalo="default",
      hound="default",
      killerbee="default",
      knight="default",
      lightninggoat="default",
      merm="default",
      mosquito="default",
      penguin="default",
      perd="default",
      pigman="default",
      spider="default",
      spider_hider="default",
      tallbird="default",
      walrus="default",
      warg="default",
      worm="default"
    },
    enabled=true
  },
  ["workshop-623749604"]={
    configuration_options={
      Craft="Normal",
      Destroyable="DestroyByPlayer",
      FoodSpoilage=1,
      Language="En",
      Position="Center",
      Slots=80
    },
    enabled=true
  },
  ["workshop-666155465"]={
    configuration_options={
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1
    },
    enabled=true
  },
  ["workshop-679636739"]={ configuration_options={  }, enabled=true },
  ["workshop-714719224"]={
    configuration_options={
      ANNOUNCE_TIP=true,
      BUFF_ITEMS=true,
      CHALLENGE_MISSION=5,
      CHALLENGE_MISSION_CD=3,
      CHALLENGE_MISSION_DIFFICULTY=0,
      CHALLENGE_MISSION_ROLL=70,
      FIRST_AID_KIT=true,
      NORMAL_ITEMS=true,
      PACKS_CD=2,
      PACKS_VALUE=1,
      RARE_ITEMS=1,
      RECORD_DEATH=true
    },
    enabled=true
  }
}
