return {
  ["workshop-1207269058"]={
    configuration_options={ ddon=true, hbcolor="dynamic", hblength=10, hbpos=1, hbstyle="heart" },
    enabled=true 
  },
  ["workshop-1234341720"]={
    configuration_options={
      battleaxe="normal",
      book_dogs="normal",
      book_freeze="normal",
      book_healing="normal",
      book_lava="normal",
      book_light="normal",
      book_meteor="normal",
      book_sleepingfield="normal",
      book_slowness="normal",
      book_summon="normal",
      book_tornado="normal",
      deathscythe="normal",
      flamesword="normal",
      halberd="normal",
      healingstaff="normal",
      katana="normal",
      pirate="normal",
      poseidon="normal",
      purplesword="normal",
      skullspear="normal",
      teleportstaff="normal" 
    },
    enabled=true 
  },
  ["workshop-367546858"]={ configuration_options={ LANG="auto", SMALL_TEXTURES=true }, enabled=true },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-458940297"]={
    configuration_options={
      DFV_ClientPrediction="default",
      DFV_FueledSettings="default",
      DFV_Language="EN",
      DFV_MinimalMode="default",
      DFV_PercentReplace="default",
      DFV_ShowACondition="default",
      DFV_ShowADefence="default",
      DFV_ShowAType="default",
      DFV_ShowDamage="default",
      DFV_ShowFireTime="default",
      DFV_ShowInsulation="default",
      DFV_ShowTemperature="default",
      DFV_ShowUses="default" 
    },
    enabled=true 
  },
  ["workshop-462434129"]={
    configuration_options={
      MOD_RESTART_ALLOW_KILL=true,
      MOD_RESTART_ALLOW_RESTART=true,
      MOD_RESTART_ALLOW_RESURRECT=true,
      MOD_RESTART_CD_BONUS=0,
      MOD_RESTART_CD_KILL=0,
      MOD_RESTART_CD_MAX=0,
      MOD_RESTART_CD_RESTART=0,
      MOD_RESTART_CD_RESURRECT=0,
      MOD_RESTART_FORCE_DROP_MODE=0,
      MOD_RESTART_IGNORING_ADMIN=true,
      MOD_RESTART_MAP_SAVE=2,
      MOD_RESTART_RESURRECT_HEALTH=0,
      MOD_RESTART_TRIGGER_MODE=1,
      MOD_RESTART_WELCOME_TIPS=true,
      MOD_RESTART_WELCOME_TIPS_TIME=6 
    },
    enabled=true 
  },
  ["workshop-462469447"]={ configuration_options={  }, enabled=true },
  ["workshop-501385076"]={ configuration_options={  }, enabled=true },
  ["workshop-572538624"]={
    configuration_options={
      IS_CHS_ALL_MOD=true,
      IS_CHS_CHARACTER=true,
      IS_CHS_FIX_ALL=true,
      IS_CHS_SETTINGS=true 
    },
    enabled=true 
  },
  ["workshop-609675532"]={
    configuration_options={
      _debug=false,
      despawn_delay=0.1,
      despawn_mode="RANDOM",
      limit_table="def",
      res_mode="MEM" 
    },
    enabled=true 
  },
  ["workshop-623749604"]={
    configuration_options={
      Craft="Normal",
      Destroyable="DestroyByPlayer",
      FoodSpoilage=0.5,
      Language="TCh",
      Position="Center",
      Slots=80 
    },
    enabled=true 
  } 
}