return {
	normal = {
		{ prefab = "blowdart_fire", tag = "weapon", chance = 1, base = 2, minday = 5, maxday = nil }, -- 燃烧吹箭
		{ prefab = "blowdart_pipe", tag = "weapon", chance = 1, base = 2, minday = 5, maxday = nil }, -- 吹箭
		{ prefab = "blowdart_sleep", tag = "weapon", chance = 1, base = 2, minday = 5, maxday = nil }, -- 麻醉吹箭
		{ prefab = "blowdart_yellow", tag = "weapon", chance = 1, base = 2, minday = 5, maxday = nil }, -- 电磁吹箭
		{ prefab = "gunpowder", tag = "resource", chance = 0.5, base = 0.5, minday = 15, maxday = nil }, -- 火药
		{ prefab = "trap_teeth", tag = "tool", chance = 1, base = 1, minday = 10, maxday = nil }, -- 狗牙陷阱
		{ prefab = "bandage", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蜂蜜药膏
		{ prefab = "fertilizer", tag = "tool", chance = 1, base = 0.8, minday = 10, maxday = nil }, -- 便便篮
		{ prefab = "healingsalve", tag = "tool", chance = 1, base = 1.5, minday = 1, maxday = 30 }, -- 治疗药膏
		{ prefab = "moonrockcrater", tag = "tool", chance = 0.5, base = 0.3, minday = 15, maxday = nil }, -- 无月之眼
		{ prefab = "trap", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 陷阱
		{ prefab = "waterballoon", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 35 }, -- 水球
		{ prefab = "acorn", tag = "resource", chance = 1, base = 1, minday = 1, maxday = 35 }, -- 坚果
		{ prefab = "ash", tag = "resource", chance = 1, base = 2, minday = 1, maxday = 35 }, -- 灰烬
		{ prefab = "beardhair", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 胡须
		{ prefab = "beefalowool", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 牛毛
		{ prefab = "beeswax", tag = "resource", chance = 1, base = 1, minday = 5, maxday = nil }, -- 蜂蜡
		{ prefab = "bluegem", tag = "resource", chance = 0.8, base = 1, minday = 5, maxday = nil }, -- 蓝宝石
		{ prefab = "boards", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 木板
		{ prefab = "boneshard", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 骨片
		{ prefab = "charcoal", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 木炭
		{ prefab = "coontail", tag = "resource", chance = 1, base = 0.5, minday = 5, maxday = 35 }, -- 猫尾
		{ prefab = "cutgrass", tag = "resource", chance = 1.5, base = 1, minday = 1, maxday = nil }, -- 割下的草
		{ prefab = "cutreeds", tag = "resource", chance = 1.5, base = 1, minday = 1, maxday = nil }, -- 割好的芦苇
		{ prefab = "cutstone", tag = "resource", chance = 1, base = 2, minday = 1, maxday = nil }, -- 石砖块
		{ prefab = "dug_berrybush", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 浆果灌木丛
		{ prefab = "dug_berrybush2", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 浆果灌木丛
		{ prefab = "dug_berrybush_juicy", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蜜汁浆果丛
		{ prefab = "dug_grass", tag = "resource", chance = 1.2, base = 1, minday = 1, maxday = nil }, -- 长草簇
		{ prefab = "dug_marsh_bush", tag = "resource", chance = 1, base = 1, minday = 1, maxday = 40 }, -- 尖刺灌木
		{ prefab = "dug_sapling", tag = "resource", chance = 1.2, base = 1, minday = 1, maxday = nil }, -- 树苗
		{ prefab = "feather_canary", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 金丝羽毛
		{ prefab = "feather_crow", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 黑色羽毛
		{ prefab = "feather_robin", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 红色羽毛
		{ prefab = "feather_robin_winter", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蓝色羽毛
		{ prefab = "fence_gate_item", tag = "resource", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 木门
		{ prefab = "fence_item", tag = "resource", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 木栅栏
		{ prefab = "flint", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 燧石
		{ prefab = "foliage", tag = "resource", chance = 1, base = 1, minday = 1, maxday = 30 }, -- 树叶
		{ prefab = "fossil_piece", tag = "resource", chance = 0.8, base = 0.5, minday = 20, maxday = nil }, -- 化石碎片
		{ prefab = "furtuft", tag = "resource", chance = 1, base = 1, minday = 10, maxday = nil }, -- 毛簇
		{ prefab = "gears", tag = "resource", chance = 0.8, base = 1.5, minday = 5, maxday = nil }, -- 齿轮
		{ prefab = "giftwrap", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 彩纸
		{ prefab = "glommerfuel", tag = "resource", chance = 1, base = 1, minday = 5, maxday = nil }, -- 格罗姆的粘液
		{ prefab = "glommerwings", tag = "resource", chance = 1, base = 1, minday = 5, maxday = nil }, -- 格罗姆的翅膀
		{ prefab = "goldnugget", tag = "resource", chance = 1.5, base = 1.5, minday = 1, maxday = nil }, -- 金块
		{ prefab = "goose_feather", tag = "resource", chance = 0.5, base = 1, minday = 1, maxday = nil }, -- 掉落的羽毛
		{ prefab = "greengem", tag = "resource", chance = 0.6, base = 1, minday = 10, maxday = nil }, -- 绿宝石
		{ prefab = "guano", tag = "resource", chance = 1, base = 2.5, minday = 1, maxday = nil }, -- 鸟屎
		{ prefab = "houndstooth", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 狗牙
		{ prefab = "ice", tag = "resource", chance = 1.5, base = 2, minday = 1, maxday = nil }, -- 冰
		{ prefab = "lightbulb", tag = "resource", chance = 1, base = 2, minday = 1, maxday = nil }, -- 荧光果
		{ prefab = "livinglog", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 活木
		{ prefab = "log", tag = "resource", chance = 1.5, base = 1, minday = 1, maxday = nil }, -- 木材
		{ prefab = "lucky_goldnugget", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 金元宝
		{ prefab = "lureplantbulb", tag = "resource", chance = 1, base = 1, minday = 5, maxday = nil }, -- 多肉的球茎
		{ prefab = "manrabbit_tail", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 兔毛
		{ prefab = "marble", tag = "resource", chance = 1, base = 1.5, minday = 1, maxday = nil }, -- 大理石
		{ prefab = "marblebean", tag = "resource", chance = 1, base = 2, minday = 1, maxday = nil }, -- 大理石魔豆
		{ prefab = "moonrocknugget", tag = "resource", chance = 1, base = 1, minday = 15, maxday = nil }, -- 月之石
		{ prefab = "mosquitosack", tag = "resource", chance = 1, base = 1, minday = 1, maxday = 30 }, -- 蚊子血袋
		{ prefab = "nightmarefuel", tag = "resource", chance = 1, base = 1.5, minday = 1, maxday = nil }, -- 噩梦燃料
		{ prefab = "nitre", tag = "resource", chance = 1, base = 1.5, minday = 1, maxday = nil }, -- 硝石
		{ prefab = "opalpreciousgem", tag = "resource", chance = 1, base = 1, minday = 5, maxday = nil }, -- 闪闪发亮的宝石
		{ prefab = "orangegem", tag = "resource", chance = 0.6, base = 1, minday = 5, maxday = nil }, -- 橙宝石
		{ prefab = "papyrus", tag = "resource", chance = 1, base = 2, minday = 1, maxday = nil }, -- 莎草纸
		{ prefab = "pigskin", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 猪皮
		{ prefab = "pinecone", tag = "resource", chance = 1, base = 1, minday = 1, maxday = 35 }, -- 松果
		{ prefab = "poop", tag = "resource", chance = 1, base = 2, minday = 1, maxday = nil }, -- 便便
		{ prefab = "purplegem", tag = "resource", chance = 0.6, base = 1, minday = 5, maxday = nil }, -- 紫宝石
		{ prefab = "rabbit", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 兔子
		{ prefab = "redgem", tag = "resource", chance = 0.8, base = 1, minday = 5, maxday = nil }, -- 红宝石
		{ prefab = "rocks", tag = "resource", chance = 1, base = 3, minday = 1, maxday = nil }, -- 岩石
		{ prefab = "rope", tag = "resource", chance = 1, base = 2, minday = 1, maxday = nil }, -- 绳索
		{ prefab = "silk", tag = "resource", chance = 1, base = 1.5, minday = 1, maxday = nil }, -- 蜘蛛网
		{ prefab = "slurper_pelt", tag = "resource", chance = 1, base = 1, minday = 5, maxday = nil }, -- 缀食者之皮
		{ prefab = "slurtle_shellpieces", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 破碎的背壳
		{ prefab = "slurtleslime", tag = "resource", chance = 0.8, base = 1, minday = 1, maxday = nil }, -- 粘滑含糊虫
		{ prefab = "spidergland", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蜘蛛腺体
		{ prefab = "spore_medium", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 红色孢子
		{ prefab = "spore_small", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 绿色孢子
		{ prefab = "spore_tall", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蓝色孢子
		{ prefab = "stinger", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蜂刺
		{ prefab = "tentaclespots", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 斑点触手皮
		{ prefab = "thulecite", tag = "resource", chance = 0.5, base = 2, minday = 15, maxday = nil }, -- 铥矿
		{ prefab = "thulecite_pieces", tag = "resource", chance = 0.6, base = 2, minday = 10, maxday = nil }, -- 铥矿石碎片
		{ prefab = "transistor", tag = "resource", chance = 1, base = 1, minday = 1, maxday = 40 }, -- 电器元件
		{ prefab = "turf_carpetfloor", tag = "resource", chance = 0.5, base = 1, minday = 1, maxday = nil }, -- 地毯地板
		{ prefab = "turf_cave", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 鸟粪草地
		{ prefab = "turf_checkerfloor", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 方格地板
		{ prefab = "turf_deciduous", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 季节性草地
		{ prefab = "turf_desertdirt", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 沙地
		{ prefab = "turf_forest", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 森林草皮
		{ prefab = "turf_fungus", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 菌类草地
		{ prefab = "turf_fungus_green", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 菌类草地
		{ prefab = "turf_fungus_red", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 菌类草地
		{ prefab = "turf_grass", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 长草草皮
		{ prefab = "turf_marsh", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 沼泽草皮
		{ prefab = "turf_mud", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 泥泞草地
		{ prefab = "turf_road", tag = "resource", chance = 0.5, base = 1, minday = 1, maxday = nil }, -- 卵石路
		{ prefab = "turf_rocky", tag = "resource", chance = 0.5, base = 1, minday = 1, maxday = nil }, -- 岩石草皮
		{ prefab = "turf_savanna", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 热带草原草皮
		{ prefab = "turf_sinkhole", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 泥泞的地皮
		{ prefab = "turf_underrock", tag = "resource", chance = 0.25, base = 1, minday = 1, maxday = 30 }, -- 洞穴石地
		{ prefab = "turf_woodfloor", tag = "resource", chance = 0.5, base = 1, minday = 1, maxday = nil }, -- 木质地板
		{ prefab = "twiggy_nut", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 多枝的树的果实
		{ prefab = "twigs", tag = "resource", chance = 1.5, base = 1, minday = 1, maxday = nil }, -- 小树枝
		{ prefab = "wall_hay_item", tag = "resource", chance = 1, base = 4, minday = 1, maxday = 20 }, -- 干草墙
		{ prefab = "wall_moonrock_item", tag = "resource", chance = 1, base = 1, minday = 5, maxday = nil }, -- 月岩墙
		{ prefab = "wall_ruins_item", tag = "resource", chance = 1, base = 1, minday = 5, maxday = nil }, -- 铥矿墙壁
		{ prefab = "wall_stone_item", tag = "resource", chance = 1, base = 3, minday = 1, maxday = 30 }, -- 石墙
		{ prefab = "wall_wood_item", tag = "resource", chance = 1, base = 3, minday = 1, maxday = 20 }, -- 木墙
		{ prefab = "waxpaper", tag = "resource", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蜡纸
		{ prefab = "yellowgem", tag = "resource", chance = 0.6, base = 1, minday = 5, maxday = nil }, -- 黄宝石
		{ prefab = "rottenegg", tag = "resource", chance = 1, base = 2, minday = 1, maxday = nil }, -- 烂鸡蛋
		{ prefab = "trunk_summer", tag = "resource", chance = 0.4, base = 0.3, minday = 10, maxday = nil }, -- 红色象鼻
		{ prefab = "trunk_winter", tag = "resource", chance = 0.4, base = 0.3, minday = 10, maxday = nil }, -- 蓝色象鼻
		{ prefab = "mandrake", tag = "resource", chance = 0.4, base = 0.3, minday = 15, maxday = nil }, -- 曼德拉草
		{ prefab = "acorn_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 烤坚果
		{ prefab = "baconeggs", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 鸡蛋火腿
		{ prefab = "batwing", tag = "food", chance = 1, base = 0.5, minday = 5, maxday = nil }, -- 黑蝙蝠翅膀
		{ prefab = "batwing_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 煮熟的黑蝙蝠翅膀
		{ prefab = "berries", tag = "food", chance = 2, base = 1, minday = 1, maxday = nil }, -- 浆果
		{ prefab = "berries_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 烤浆果
		{ prefab = "berries_juicy", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蜜汁浆果
		{ prefab = "berries_juicy_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 烤蜜汁浆果
		{ prefab = "bird_egg", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 鸡蛋
		{ prefab = "bird_egg_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 熟鸡蛋
		{ prefab = "blue_cap", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蓝菇头
		{ prefab = "blue_cap_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 烤蓝蘑菇
		{ prefab = "bonestew", tag = "food", chance = 2, base = 0.8, minday = 5, maxday = nil }, -- 肉汤
		{ prefab = "butter", tag = "food", chance = 1, base = 0.6, minday = 5, maxday = nil }, -- 蝴蝶黄油
		{ prefab = "butterflymuffin", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 奶油松饼
		{ prefab = "butterflywings", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蝴蝶翅膀
		{ prefab = "cactus_flower", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 仙人掌花
		{ prefab = "cactus_meat", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 仙人掌肉
		{ prefab = "cactus_meat_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 煮好的仙人掌肉
		{ prefab = "carrot", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 胡萝卜
		{ prefab = "carrot_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = 20 }, -- 烤胡萝卜
		{ prefab = "carrot_seeds", tag = "food", chance = 0.5, base = 1.5, minday = 1, maxday = nil }, -- 胡萝卜种子
		{ prefab = "cave_banana", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 洞穴香蕉
		{ prefab = "cave_banana_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 煮熟的香蕉
		{ prefab = "cookedmeat", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 熟肉
		{ prefab = "cookedmonstermeat", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 熟怪兽肉
		{ prefab = "cookedsmallmeat", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 熟肉块
		{ prefab = "corn", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 玉米
		{ prefab = "corn_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = 15 }, -- 爆米花
		{ prefab = "corn_seeds", tag = "food", chance = 0.5, base = 1.5, minday = 1, maxday = nil }, -- 玉米种子
		{ prefab = "dragonfruit", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 火龙果
		{ prefab = "dragonfruit_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 精致火龙果
		{ prefab = "dragonfruit_seeds", tag = "food", chance = 0.5, base = 1.5, minday = 1, maxday = nil }, -- 火龙果种子
		{ prefab = "dragonpie", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 火龙果派
		{ prefab = "drumstick", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 鸡腿
		{ prefab = "drumstick_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 炸鸡腿
		{ prefab = "durian", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 榴莲
		{ prefab = "durian_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 超臭榴莲
		{ prefab = "durian_seeds", tag = "food", chance = 0.5, base = 1.5, minday = 1, maxday = nil }, -- 榴莲种子
		{ prefab = "eel", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 鳗鱼
		{ prefab = "eel_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 煮熟的鳗鱼
		{ prefab = "eggplant", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 茄子
		{ prefab = "eggplant_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 红烧茄子
		{ prefab = "eggplant_seeds", tag = "food", chance = 0.5, base = 1.5, minday = 1, maxday = nil }, -- 茄子种子
		{ prefab = "fish", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 鱼
		{ prefab = "fish_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 熟鱼
		{ prefab = "fishsticks", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 炸鱼条
		{ prefab = "fishtacos", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 鱼炸玉米饼
		{ prefab = "flowersalad", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 花瓣沙拉
		{ prefab = "frogglebunwich", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 青蛙圆面包三明治
		{ prefab = "froglegs", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 青蛙腿
		{ prefab = "froglegs_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 熟青蛙腿
		{ prefab = "fruitmedley", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 水果拼盘
		{ prefab = "goatmilk", tag = "food", chance = 1, base = 0.5, minday = 1, maxday = nil }, -- 电羊奶
		{ prefab = "green_cap", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 绿菇头
		{ prefab = "green_cap_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 烤绿蘑菇
		{ prefab = "guacamole", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 地鼠肉
		{ prefab = "honey", tag = "food", chance = 3, base = 1, minday = 1, maxday = nil }, -- 蜂蜜
		{ prefab = "honeyham", tag = "food", chance = 2, base = 1, minday = 1, maxday = nil }, -- 蜜汁火腿
		{ prefab = "honeynuggets", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 甜蜜金砖
		{ prefab = "hotchili", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 辣椒酱
		{ prefab = "icecream", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 冰淇淋
		{ prefab = "jammypreserves", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 果酱蜜饯
		{ prefab = "jellybean", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 果冻豆
		{ prefab = "kabobs", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 肉串
		{ prefab = "meat", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 肉
		{ prefab = "meat_dried", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 肉干
		{ prefab = "meatballs", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 肉丸
		{ prefab = "monstermeat", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 怪兽肉
		{ prefab = "monstermeat_dried", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 怪兽肉干
		{ prefab = "perogies", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 饺子
		{ prefab = "petals", tag = "food", chance = 1, base = 1, minday = 1, maxday = 20 }, -- 花瓣
		{ prefab = "petals_evil", tag = "food", chance = 1, base = 1, minday = 1, maxday = 20 }, -- 恶魔花瓣
		{ prefab = "plantmeat", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 多叶的肉
		{ prefab = "plantmeat_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 煮熟的多叶肉
		{ prefab = "pomegranate", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 石榴
		{ prefab = "pomegranate_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 石榴片
		{ prefab = "pomegranate_seeds", tag = "food", chance = 0.5, base = 1.5, minday = 1, maxday = nil }, -- 石榴种子
		{ prefab = "powcake", tag = "food", chance = 1, base = 0.2, minday = 10, maxday = 40 }, -- 芝士蛋糕
		{ prefab = "pumpkin", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 南瓜
		{ prefab = "pumpkin_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 热南瓜
		{ prefab = "pumpkin_seeds", tag = "food", chance = 0.5, base = 1.5, minday = 1, maxday = nil }, -- 南瓜种子
		{ prefab = "pumpkincookie", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 南瓜饼
		{ prefab = "ratatouille", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蔬菜杂烩
		{ prefab = "red_cap", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 红菇头
		{ prefab = "red_cap_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 烤红蘑菇
		{ prefab = "royal_jelly", tag = "food", chance = 1, base = 1, minday = 15, maxday = nil }, -- 蜂王浆
		{ prefab = "seeds", tag = "food", chance = 1, base = 1, minday = 1, maxday = 40 }, -- 种子
		{ prefab = "seeds_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 烤种子
		{ prefab = "smallmeat", tag = "food", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 小肉块
		{ prefab = "smallmeat_dried", tag = "food", chance = 1, base = 1, minday = 1, maxday = 25 }, -- 小块肉干
		{ prefab = "stuffedeggplant", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 香酥茄盒
		{ prefab = "taffy", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 太妃糖
		{ prefab = "tallbirdegg", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 高脚鸟蛋
		{ prefab = "tallbirdegg_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 油煎高脚鸟蛋
		{ prefab = "tallbirdegg_cracked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 孵化的高脚鸟蛋
		{ prefab = "trailmix", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 水果杂烩
		{ prefab = "trunk_cooked", tag = "food", chance = 1, base = 1, minday = 5, maxday = nil }, -- 烤熟象鼻
		{ prefab = "turkeydinner", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 火鸡正餐
		{ prefab = "cutlichen", tag = "food", chance = 1, base = 2.5, minday = 1, maxday = 20 }, -- 苔藓
		{ prefab = "unagi", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 鳗鱼
		{ prefab = "waffles", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 华夫饼
		{ prefab = "watermelon", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 西瓜
		{ prefab = "watermelon_cooked", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 烤西瓜
		{ prefab = "watermelon_seeds", tag = "food", chance = 0.5, base = 1.5, minday = 1, maxday = nil }, -- 西瓜种子
		{ prefab = "watermelonicle", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 西瓜冰
		{ prefab = "wormlight", tag = "food", chance = 1, base = 0.5, minday = 5, maxday = nil }, -- 发光浆果
		{ prefab = "wormlight_lesser", tag = "food", chance = 1, base = 1, minday = 1, maxday = nil }, -- 小发光浆果
		{ prefab = "cookedmandrake", tag = "food", chance = 1, base = 0.3, minday = 15, maxday = nil }, -- 熟曼德拉草
		{ prefab = "mandrakesoup", tag = "food", chance = 1, base = 0.3, minday = 15, maxday = nil }, -- 曼德拉草汤
	},
	rare = {
		{ prefab = "heatrock", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 15 }, -- 热能石
		{ prefab = "lantern", tag = "tool", chance = 2, base = 1, minday = 1, maxday = 15 }, -- 提灯
		{ prefab = "redlantern", tag = "tool", chance = 2, base = 1, minday = 5, maxday = 15 }, -- 红灯笼
		{ prefab = "goldenaxe", tag = "tool", chance = 3, base = 1, minday = 1, maxday = 20 }, -- 金斧头
		{ prefab = "goldenpickaxe", tag = "tool", chance = 3, base = 1, minday = 1, maxday = 20 }, -- 黄金鹤嘴锄
		{ prefab = "goldenshovel", tag = "tool", chance = 3, base = 1, minday = 1, maxday = 20 }, -- 黄金铁铲
		{ prefab = "fishingrod", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 钓竿
		{ prefab = "pumpkin_lantern", tag = "tool", chance = 2, base = 1, minday = 1, maxday = 25 }, -- 南瓜灯
		{ prefab = "reviver", tag = "tool", chance = 2, base = 1.5, minday = 1, maxday = nil }, -- 救赎之心
		{ prefab = "horn", tag = "resource", chance = 1, base = 1, minday = 1, maxday = 40 }, -- 牛角
		{ prefab = "saddle_basic", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 20 }, -- 鞍
		{ prefab = "saddlehorn", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 15 }, -- 取鞍器
		{ prefab = "sewing_kit", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 25 }, -- 缝纫工具包
		{ prefab = "umbrella", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 雨伞
		{ prefab = "grass_umbrella", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 漂亮太阳伞
		{ prefab = "featherpencil", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 羽毛笔
		{ prefab = "bedroll_straw", tag = "tool", chance = 2, base = 1, minday = 1, maxday = 10 }, -- 稻草卷
		{ prefab = "bedroll_furry", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 25 }, -- 毛皮铺盖
		{ prefab = "minerhat", tag = "tool", chance = 2, base = 1, minday = 1, maxday = 25 }, -- 矿工帽
		{ prefab = "compass", tag = "tool", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 指南针
		{ prefab = "spear", tag = "weapon", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 长矛
		{ prefab = "spear_wathgrithr", tag = "weapon", chance = 3, base = 1, minday = 1, maxday = 15 }, -- 战斗长矛
		{ prefab = "boomerang", tag = "weapon", chance = 1, base = 1, minday = 1, maxday = 15 }, -- 回旋镖
		{ prefab = "footballhat", tag = "weapon", chance = 3, base = 1, minday = 1, maxday = 10 }, -- 猪皮足球头盔
		{ prefab = "armorwood", tag = "weapon", chance = 3, base = 1, minday = 1, maxday = 10 }, -- 木制盔甲
		{ prefab = "tentaclespike", tag = "weapon", chance = 1, base = 1, minday = 1, maxday = 30 }, -- 触手尖刺
		{ prefab = "whip", tag = "weapon", chance = 1, base = 1, minday = 1, maxday = 25 }, -- 三尾猫的教诲
		{ prefab = "hambat", tag = "weapon", chance = 3, base = 1, minday = 1, maxday = 35 }, -- 火腿球棒
		{ prefab = "beemine", tag = "tool", chance = 1.5, base = 1, minday = 5, maxday = 25 }, -- 蜜蜂地雷
		{ prefab = "beefalohat", tag = "clothe", chance = 1, base = 1, minday = 1, maxday = 30 }, -- 牛帽
		{ prefab = "beehat", tag = "clothe", chance = 1, base = 1, minday = 5, maxday = 20 }, -- 养蜂人的帽子
		{ prefab = "bushhat", tag = "clothe", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 丛林帽
		{ prefab = "catcoonhat", tag = "clothe", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 猫帽
		{ prefab = "earmuffshat", tag = "clothe", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 兔毛耳套
		{ prefab = "flowerhat", tag = "clothe", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 花环
		{ prefab = "hawaiianshirt", tag = "clothe", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 花纹衬衫
		{ prefab = "icehat", tag = "clothe", chance = 1, base = 1, minday = 1, maxday = 20 }, -- 冰块
		{ prefab = "raincoat", tag = "clothe", chance = 2, base = 1, minday = 1, maxday = 25 }, -- 雨衣
		{ prefab = "rainhat", tag = "clothe", chance = 2, base = 1, minday = 1, maxday = 25 }, -- 雨帽
		{ prefab = "reflectivevest", tag = "clothe", chance = 1, base = 1, minday = 5, maxday = 40 }, -- 夏季背心
		{ prefab = "sweatervest", tag = "clothe", chance = 1, base = 1, minday = 5, maxday = 40 }, -- 小巧背心
		{ prefab = "tophat", tag = "clothe", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 高礼帽
		{ prefab = "walrushat", tag = "clothe", chance = 1.5, base = 1, minday = 1, maxday = nil }, -- 贝雷帽
		{ prefab = "watermelonhat", tag = "clothe", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 时尚西瓜帽
		{ prefab = "winterhat", tag = "clothe", chance = 1, base = 1, minday = 5, maxday = 25 }, -- 寒冬帽
		{ prefab = "featherhat", tag = "clothe", chance = 1, base = 1, minday = 1, maxday = 15 }, -- 羽毛帽
		{ prefab = "piggyback", tag = "clothe", chance = 1, base = 1, minday = 10, maxday = nil }, -- 小猪包
		{ prefab = "walrus_tusk", tag = "resource", chance = 1, base = 0.5, minday = 10, maxday = nil }, -- 海象牙
		{ prefab = "steelwool", tag = "resource", chance = 1, base = 0.5, minday = 10, maxday = nil }, -- 钢丝绒
		{ prefab = "lightninggoathorn", tag = "resource", chance = 0.5, base = 1, minday = 5, maxday = nil }, -- 电羊角
		{ prefab = "trunkvest_summer", tag = "clothe", chance = 1, base = 1, minday = 5, maxday = nil }, -- 夏日背心
		{ prefab = "trunkvest_winter", tag = "clothe", chance = 1, base = 1, minday = 5, maxday = nil }, -- 寒冬背心
		{ prefab = "red_mushroomhat", tag = "clothe", chance = 2, base = 1, minday = 10, maxday = 50 }, -- 红菇帽
		{ prefab = "blue_mushroomhat", tag = "clothe", chance = 2, base = 1, minday = 10, maxday = 50 }, -- 蓝菇帽
		{ prefab = "green_mushroomhat", tag = "clothe", chance = 2, base = 1, minday = 10, maxday = 50 }, -- 绿菇帽
		{ prefab = "molehat", tag = "clothe", chance = 1.5, base = 1, minday = 25, maxday = nil }, -- 地鼠帽
		{ prefab = "lifeinjector", tag = "tool", chance = 1, base = 1, minday = 1, maxday = nil }, -- AGV试验药
		{ prefab = "nightsword", tag = "weapon", chance = 1, base = 1, minday = 5, maxday = nil }, -- 影刀
		{ prefab = "spiderhat", tag = "clothe", chance = 1, base = 1, minday = 5, maxday = nil }, -- 蜘蛛帽
		{ prefab = "armorsnurtleshell", tag = "weapon", chance = 1, base = 1, minday = 10, maxday = nil }, -- 圆壳蛞蝓壳
		{ prefab = "armor_sanity", tag = "weapon", chance = 2, base = 1, minday = 5, maxday = nil }, -- 暗影之甲
		{ prefab = "armormarble", tag = "weapon", chance = 2, base = 1, minday = 10, maxday = nil }, -- 大理石盔甲
		{ prefab = "slurtlehat", tag = "weapon", chance = 1.5, base = 1, minday = 10, maxday = nil }, -- 背壳头盔
		{ prefab = "wathgrithrhat", tag = "weapon", chance = 3, base = 1, minday = 1, maxday = 35 }, -- 战斗头盔
		{ prefab = "armorslurper", tag = "weapon", chance = 1, base = 1, minday = 10, maxday = nil }, -- 饥饿腰带
		{ prefab = "panflute", tag = "weapon", chance = 1, base = 1, minday = 5, maxday = nil }, -- 排箫
		{ prefab = "nightstick", tag = "weapon", chance = 1.5, base = 1, minday = 10, maxday = nil }, -- 晨星
		{ prefab = "batbat", tag = "weapon", chance = 2, base = 1, minday = 10, maxday = nil }, -- 蝙蝠斧棍
		{ prefab = "amulet", tag = "clothe", chance = 3, base = 1, minday = 1, maxday = nil }, -- 提神护符
		{ prefab = "blueamulet", tag = "clothe", chance = 1, base = 1, minday = 1, maxday = nil }, -- 寒冰护符
		{ prefab = "multitool_axe_pickaxe", tag = "tool", chance = 2, base = 1, minday = 10, maxday = nil }, -- 镐斧
		{ prefab = "onemanband", tag = "tool", chance = 2, base = 1, minday = 5, maxday = nil }, -- 独奏乐器
		{ prefab = "firestaff", tag = "weapon", chance = 3, base = 1, minday = 5, maxday = 40 }, -- 火魔杖
		{ prefab = "icestaff", tag = "weapon", chance = 3, base = 1, minday = 5, maxday = 40 }, -- 冰魔杖
		{ prefab = "spidereggsack", tag = "resource", chance = 2, base = 0.7, minday = 5, maxday = nil }, -- 蜘蛛卵
		{ prefab = "honeycomb", tag = "resource", chance = 2, base = 0.7, minday = 5, maxday = nil }, -- 蜂巢
		{ prefab = "redmooneye", tag = "tool", chance = 0.5, base = 1, minday = 15, maxday = nil }, -- 红月之眼
		{ prefab = "bluemooneye", tag = "tool", chance = 0.5, base = 1, minday = 15, maxday = nil }, -- 蓝月之眼
		{ prefab = "greenmooneye", tag = "tool", chance = 0.5, base = 1, minday = 15, maxday = nil }, -- 绿月之眼
		{ prefab = "purplemooneye", tag = "tool", chance = 0.5, base = 1, minday = 15, maxday = nil }, -- 紫月之眼
		{ prefab = "orangemooneye", tag = "tool", chance = 0.5, base = 1, minday = 15, maxday = nil }, -- 橙月之眼
		{ prefab = "yellowmooneye", tag = "tool", chance = 0.5, base = 1, minday = 15, maxday = nil }, -- 黄月之眼
		{ prefab = "cane", tag = "tool", chance = 2, base = 1, minday = 5, maxday = nil }, -- 步行手杖
		{ prefab = "greenamulet", tag = "clothe", chance = 1, base = 1, minday = 10, maxday = nil }, -- 建造护符
		{ prefab = "opalstaff", tag = "tool", chance = 1, base = 1, minday = 10, maxday = nil }, -- 呼月之杖
		{ prefab = "featherfan", tag = "tool", chance = 1, base = 1, minday = 5, maxday = 45 }, -- 鹅毛扇
		{ prefab = "minifan", tag = "tool", chance = 1, base = 1, minday = 15, maxday = nil }, -- 旋风扇
		{ prefab = "perdfan", tag = "tool", chance = 1, base = 1, minday = 15, maxday = nil }, -- 幸运扇
		{ prefab = "beargervest", tag = "clothe", chance = 1, base = 1, minday = 15, maxday = nil }, -- 熊皮背心
		{ prefab = "eyebrellahat", tag = "clothe", chance = 1, base = 1, minday = 15, maxday = nil }, -- 眼球伞
		{ prefab = "icepack", tag = "clothe", chance = 1, base = 1, minday = 20, maxday = nil }, -- 隔热包
		{ prefab = "orangeamulet", tag = "clothe", chance = 1, base = 1, minday = 15, maxday = nil }, -- 懒惰的强盗
		{ prefab = "purpleamulet", tag = "clothe", chance = 1, base = 1, minday = 15, maxday = nil }, -- 梦魇护符
		{ prefab = "staff_tornado", tag = "weapon", chance = 1, base = 1, minday = 15, maxday = nil }, -- 旋风
		{ prefab = "telestaff", tag = "tool", chance = 1, base = 1, minday = 15, maxday = nil }, -- 传送权杖
		{ prefab = "yellowamulet", tag = "clothe", chance = 1, base = 1, minday = 15, maxday = nil }, -- 魔力之光
		{ prefab = "yellowstaff", tag = "tool", chance = 1, base = 1, minday = 15, maxday = nil }, -- 星星呼唤者权杖
		{ prefab = "ruins_bat", tag = "weapon", chance = 2, base = 1, minday = 10, maxday = nil }, -- 铥矿棒
		{ prefab = "ruinshat", tag = "weapon", chance = 2, base = 1, minday = 10, maxday = nil }, -- 铥矿石皇冠
		{ prefab = "orangestaff", tag = "tool", chance = 1, base = 1, minday = 10, maxday = nil }, -- 懒惰的探索者
		{ prefab = "greenstaff", tag = "tool", chance = 1, base = 1, minday = 20, maxday = nil }, -- 毁灭权杖
		{ prefab = "saddle_race", tag = "tool", chance = 1, base = 1, minday = 25, maxday = 60 }, -- 闪亮之鞍
		{ prefab = "saddle_war", tag = "tool", chance = 1, base = 1, minday = 30, maxday = 60 }, -- 浴血战鞍
		{ prefab = "phlegm", tag = "resource", chance = 1, base = 0.5, minday = 15, maxday = nil }, -- 痰
		{ prefab = "bearger_fur", tag = "resource", chance = 1, base = 0.5, minday = 15, maxday = nil }, -- 厚皮毛
		{ prefab = "turf_dragonfly", tag = "resource", chance = 1, base = 0.6, minday = 25, maxday = nil }, -- 龙鳞地板
		{ prefab = "dragon_scales", tag = "resource", chance = 1, base = 0.5, minday = 25, maxday = nil }, -- 鳞片
		{ prefab = "deerclops_eyeball", tag = "resource", chance = 1, base = 0.5, minday = 20, maxday = nil }, -- 巨鹿眼球
		{ prefab = "minotaurhorn", tag = "resource", chance = 1, base = 0.4, minday = 25, maxday = nil }, -- 守卫者的角
		{ prefab = "klaussackkey", tag = "resource", chance = 0.8, base = 0.4, minday = 25, maxday = nil }, -- 牡鹿之匙
		{ prefab = "deer_antler1", tag = "resource", chance = 0.5, base = 0.4, minday = 20, maxday = nil }, -- 鹿之匙
		{ prefab = "deer_antler2", tag = "resource", chance = 0.5, base = 0.4, minday = 20, maxday = nil }, -- 鹿之匙
		{ prefab = "deer_antler3", tag = "resource", chance = 0.5, base = 0.4, minday = 20, maxday = nil }, -- 鹿之匙
		{ prefab = "shadowheart", tag = "resource", chance = 1, base = 0.3, minday = 35, maxday = nil }, -- 暗影之心
		{ prefab = "shroom_skin", tag = "resource", chance = 1, base = 0.3, minday = 40, maxday = nil }, -- 蕈蟾酥
		{ prefab = "krampus_sack", tag = "clothe", chance = 0.8, base = 1, minday = 30, maxday = nil }, -- 坎普斯背包
		{ prefab = "armorruins", tag = "weapon", chance = 1.2, base = 1, minday = 10, maxday = nil }, -- 铥矿甲胄
		{ prefab = "armordragonfly", tag = "weapon", chance = 1.2, base = 1, minday = 15, maxday = nil }, -- 鳞甲
		{ prefab = "hivehat", tag = "weapon", chance = 1, base = 1, minday = 25, maxday = nil }, -- 蜂王冠
		{ prefab = "eyeturret_item", tag = "weapon", chance = 0.8, base = 1, minday = 35, maxday = nil }, -- 恒迪尤斯·舒提尤斯
	},
	building = {
		{ prefab = "flower_cave", tag = "building", chance = 3, base = 1, minday = 1, maxday = 10 }, -- 荧光草
		{ prefab = "flower_cave_double", tag = "building", chance = 2, base = 1, minday = 5, maxday = nil }, -- 荧光草
		{ prefab = "flower_cave_triple", tag = "building", chance = 1, base = 1, minday = 10, maxday = nil }, -- 荧光草
		{ prefab = "cave_banana_tree", tag = "building", chance = 1, base = 1, minday = 5, maxday = nil }, -- 洞穴香蕉树
		{ prefab = "pighead", tag = "building", chance = 2, base = 1, minday = 1, maxday = 10 }, -- 猪人头
		{ prefab = "mermhead", tag = "building", chance = 2, base = 1, minday = 1, maxday = 10 }, -- 鱼人头
		{ prefab = "rabbithole", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 兔子窝
		{ prefab = "campfire", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 营火
		{ prefab = "coldfire", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 吸热营火
		{ prefab = "firepit", tag = "building", chance = 2, base = 1, minday = 1, maxday = 10 }, -- 石头篝火
		{ prefab = "coldfirepit", tag = "building", chance = 2, base = 1, minday = 1, maxday = 10 }, -- 吸热篝火
		{ prefab = "fence", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 木栅栏
		{ prefab = "fence_gate", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 木门
		{ prefab = "cookpot", tag = "building", chance = 2, base = 1, minday = 1, maxday = 10 }, -- 烹煮锅
		{ prefab = "icebox", tag = "building", chance = 2, base = 1, minday = 1, maxday = 10 }, -- 冰箱
		{ prefab = "treasurechest", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 宝箱
		{ prefab = "pandoraschest", tag = "building", chance = 1.5, base = 1, minday = 5, maxday = 10 }, -- 装饰箱
		{ prefab = "skullchest", tag = "building", chance = 1.5, base = 1, minday = 5, maxday = 10 }, -- 骷髅箱
		{ prefab = "minotaurchest", tag = "building", chance = 1.5, base = 1, minday = 10, maxday = nil }, -- 大豪华箱子
		{ prefab = "lightning_rod", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 避雷针
		{ prefab = "rainometer", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 雨量计
		{ prefab = "winterometer", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 温度测量器
		{ prefab = "meatrack", tag = "building", chance = 2, base = 1, minday = 1, maxday = 10 }, -- 晒肉架
		{ prefab = "birdcage", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 鸟笼
		{ prefab = "scarecrow", tag = "building", chance = 1, base = 1, minday = 1, maxday = nil }, -- 友善的草人
		{ prefab = "siestahut", tag = "building", chance = 1.5, base = 1, minday = 1, maxday = 10 }, -- 简易小木棚
		{ prefab = "tent", tag = "building", chance = 2, base = 1, minday = 1, maxday = 30 }, -- 帐篷
		{ prefab = "resurrectionstatue", tag = "building", chance = 1, base = 1, minday = 5, maxday = 30 }, -- 肉块雕像
		{ prefab = "researchlab", tag = "building", chance = 2, base = 1, minday = 1, maxday = 10 }, -- 科学机器
		{ prefab = "researchlab2", tag = "building", chance = 2, base = 1, minday = 5, maxday = 15 }, -- 炼金术引擎
		{ prefab = "wall_stone", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 石墙
		{ prefab = "wall_wood", tag = "building", chance = 1, base = 1, minday = 1, maxday = 10 }, -- 木墙
		{ prefab = "ruins_statue_head", tag = "building", chance = 2, base = 1, minday = 10, maxday = nil }, -- 远古雕像 宝石...
		{ prefab = "ruins_statue_head_nogem", tag = "building", chance = 1, base = 1, minday = 10, maxday = nil }, -- 远古雕像
		{ prefab = "ruins_statue_mage", tag = "building", chance = 1.5, base = 1, minday = 10, maxday = nil }, -- 远古雕像 宝石...
		{ prefab = "ruins_statue_mage_nogem", tag = "building", chance = 1, base = 1, minday = 10, maxday = nil }, -- 远古雕像
		{ prefab = "cartographydesk", tag = "building", chance = 1, base = 1, minday = 5, maxday = 15 }, -- 制图桌
		{ prefab = "sculptingtable", tag = "building", chance = 1, base = 1, minday = 5, maxday = 15 }, -- 陶艺转盘
		{ prefab = "slow_farmplot", tag = "building", chance = 2, base = 1, minday = 1, maxday = 15 }, -- 基本农场
		{ prefab = "fast_farmplot", tag = "building", chance = 2, base = 1, minday = 5, maxday = nil }, -- 高级农场
		{ prefab = "mushroom_farm", tag = "building", chance = 1.5, base = 1, minday = 10, maxday = nil }, -- 蘑菇农场
		{ prefab = "beebox", tag = "building", chance = 1, base = 1, minday = 5, maxday = 20 }, -- 蜂箱
		{ prefab = "firesuppressor", tag = "building", chance = 1.5, base = 1, minday = 5, maxday = 10 }, -- 雪球发射机
		{ prefab = "nightlight", tag = "building", chance = 2, base = 1, minday = 5, maxday = 30 }, -- 暗夜照明灯
		{ prefab = "pigtorch", tag = "building", chance = 1.5, base = 1, minday = 1, maxday = nil }, -- 猪头火炬
		{ prefab = "green_mushroom", tag = "building", chance = 1, base = 1, minday = 1, maxday = 15 }, -- 绿蘑菇
		{ prefab = "beehive", tag = "building", chance = 1, base = 1, minday = 1, maxday = nil }, -- 蜂窝
		{ prefab = "wasphive", tag = "building", chance = 1.5, base = 1, minday = 10, maxday = nil }, -- 杀人蜂巢
		{ prefab = "catcoonden", tag = "building", chance = 1, base = 1, minday = 1, maxday = nil }, -- 中空树桩
		{ prefab = "houndmound", tag = "building", chance = 1, base = 1, minday = 10, maxday = nil }, -- 猎犬丘
		{ prefab = "mermhouse", tag = "building", chance = 1, base = 1, minday = 1, maxday = nil }, -- 鱼族废墟
		{ prefab = "monkeybarrel", tag = "building", chance = 1, base = 1, minday = 1, maxday = nil }, -- 暴躁猴群
		{ prefab = "pighouse", tag = "building", chance = 2, base = 1, minday = 1, maxday = 25 }, -- 猪舍
		{ prefab = "tallbirdnest", tag = "building", chance = 1, base = 1, minday = 5, maxday = 30 }, -- 高脚鸟巢穴
		{ prefab = "rabbithouse", tag = "building", chance = 1.5, base = 1, minday = 1, maxday = nil }, -- 兔子窝
		{ prefab = "slurtlehole", tag = "building", chance = 1, base = 1, minday = 5, maxday = nil }, -- 含糊虫土堆
		{ prefab = "spiderden", tag = "building", chance = 1.5, base = 1, minday = 5, maxday = 25 }, -- 蜘蛛巢
		{ prefab = "spiderden_2", tag = "building", chance = 1, base = 1, minday = 10, maxday = 35 }, -- 蜘蛛巢2
		{ prefab = "spiderden_3", tag = "building", chance = 0.8, base = 1, minday = 15, maxday = nil }, -- 蜘蛛巢3
		{ prefab = "spiderhole", tag = "building", chance = 1.5, base = 1, minday = 25, maxday = nil }, -- 蛛网岩
		{ prefab = "beemine_maxwell", tag = "building", chance = 2, base = 1, minday = 1, maxday = 40 }, -- 麦斯威尔的蜜蜂炸弹
		{ prefab = "trap_teeth_maxwell", tag = "building", chance = 2, base = 1, minday = 1, maxday = nil }, -- 麦斯威尔的利齿陷阱
		{ prefab = "sentryward", tag = "building", chance = 1, base = 1, minday = 20, maxday = 35 }, -- 真眼守卫
		{ prefab = "researchlab3", tag = "building", chance = 1.5, base = 1, minday = 1, maxday = 35 }, -- 暗影操纵仪
		{ prefab = "researchlab4", tag = "building", chance = 2, base = 1, minday = 1, maxday = 35 }, -- 魔法帽子
		{ prefab = "dragonflychest", tag = "building", chance = 1, base = 1, minday = 20, maxday = nil }, -- 鳞片箱子
		{ prefab = "perdshrine", tag = "building", chance = 1, base = 1, minday = 20, maxday = 35 }, -- 火鸡祭坛
		{ prefab = "mushroom_light", tag = "building", chance = 0.8, base = 1, minday = 25, maxday = nil }, -- 荧菇灯
		{ prefab = "mushroom_light2", tag = "building", chance = 0.8, base = 1, minday = 25, maxday = nil }, -- 炽菇灯
		{ prefab = "wall_moonrock", tag = "building", chance = 1.5, base = 1, minday = 15, maxday = nil }, -- 月岩墙
		{ prefab = "wall_ruins", tag = "building", chance = 1.5, base = 1, minday = 15, maxday = nil }, -- 铥矿墙壁
		{ prefab = "dragonflyfurnace", tag = "building", chance = 0.5, base = 1, minday = 30, maxday = nil }, -- 龙鳞熔炉
		{ prefab = "eyeturret", tag = "building", chance = 0.5, base = 1, minday = 25, maxday = nil }, -- 恒迪尤斯·舒提尤斯
		{ prefab = "ancient_altar_spawner", tag = "building", chance = 0.3, base = 1, minday = 35, maxday = nil }, -- 远古遗迹
		{ prefab = "ancient_altar_broken_spawner", tag = "building", chance = 0.5, base = 1, minday = 30, maxday = nil }, -- 破碎的远古遗迹
	},
	monster = {
		{ prefab = "frog", tag = "living", chance = 1, base = 2, minday = 1, maxday = nil }, -- 青蛙
		{ prefab = "catcoon", tag = "living", chance = 1, base = 3, minday = 1, maxday = 25 }, -- 猫熊
		{ prefab = "killerbee", tag = "living", chance = 1, base = 4, minday = 1, maxday = 25 }, -- 杀人蜂
		{ prefab = "bat", tag = "living", chance = 1, base = 4, minday = 1, maxday = 25 }, -- 黑蝙蝠
		{ prefab = "hound", tag = "living", chance = 1.5, base = 3, minday = 1, maxday = 35 }, -- 猎犬
		{ prefab = "firehound", tag = "living", chance = 1.5, base = 3, minday = 5, maxday = 35 }, -- 红色猎犬
		{ prefab = "icehound", tag = "living", chance = 1, base = 3.5, minday = 5, maxday = 35 }, -- 蓝色猎犬
		{ prefab = "beefalo", tag = "living", chance = 1.5, base = 3, minday = 1, maxday = 35 }, -- 皮弗娄牛
		{ prefab = "tallbird", tag = "living", chance = 1.5, base = 3, minday = 5, maxday = 35 }, -- 高脚鸟
		{ prefab = "monkey", tag = "living", chance = 1, base = 0.3, minday = 5, maxday = 25 }, -- 暴躁猴
		{ prefab = "bunnyman", tag = "living", chance = 1.5, base = 2, minday = 5, maxday = 35 }, -- 兔男
		{ prefab = "lightninggoat", tag = "living", chance = 1, base = 0.4, minday = 10, maxday = 45 }, -- 电羊
		{ prefab = "merm", tag = "living", chance = 1, base = 3, minday = 2, maxday = 25 }, -- 鱼人
		{ prefab = "pigman", tag = "living", chance = 1, base = 3, minday = 2, maxday = 25 }, -- 猪人
		{ prefab = "pigguard", tag = "living", chance = 1.5, base = 3.5, minday = 5, maxday = 35 }, -- 警卫猪
		{ prefab = "slurtle", tag = "living", chance = 1, base = 0.4, minday = 5, maxday = 40 }, -- 含糊虫
		{ prefab = "snurtle", tag = "living", chance = 1, base = 0.4, minday = 5, maxday = 40 }, -- 黏糊虫
		{ prefab = "spider", tag = "living", chance = 1, base = 3, minday = 1, maxday = 35 }, -- 蜘蛛
		{ prefab = "spider_dropper", tag = "living", chance = 1.5, base = 1, minday = 5, maxday = 45 }, -- 白蜘蛛
		{ prefab = "spider_hider", tag = "living", chance = 1.5, base = 2, minday = 10, maxday = 45 }, -- 洞穴蜘蛛
		{ prefab = "spider_spitter", tag = "living", chance = 1, base = 2, minday = 1, maxday = 45 }, -- 喷吐虫
		{ prefab = "spider_warrior", tag = "living", chance = 2, base = 2.5, minday = 15, maxday = nil }, -- 蜘蛛战士
		{ prefab = "knight_nightmare", tag = "living", chance = 1, base = 2, minday = 5, maxday = 35 }, -- 损坏的骑士
		{ prefab = "bishop_nightmare", tag = "living", chance = 1, base = 2, minday = 5, maxday = 35 }, -- 损坏的象
		{ prefab = "rook_nightmare", tag = "living", chance = 1, base = 1, minday = 15, maxday = 35 }, -- 损坏的战车
		{ prefab = "koalefant_summer", tag = "living", chance = 1, base = 0.5, minday = 10, maxday = 35 }, -- 蓝象
		{ prefab = "koalefant_winter", tag = "living", chance = 2, base = 1, minday = 10, maxday = 35 }, -- 蓝色象鼻怪
		{ prefab = "worm", tag = "living", chance = 1.5, base = 1, minday = 15, maxday = nil }, -- 深渊蠕虫
		{ prefab = "walrus", tag = "living", chance = 1, base = 1.5, minday = 1, maxday = 35 }, -- 海象
		{ prefab = "tentacle", tag = "living", chance = 1, base = 0.8, minday = 10, maxday = nil }, -- 触手
		{ prefab = "knight", tag = "living", chance = 1, base = 2.5, minday = 1, maxday = 35 }, -- 发条骑士
		{ prefab = "bishop", tag = "living", chance = 1.5, base = 1.5, minday = 1, maxday = 35 }, -- 发条主教
		{ prefab = "rook", tag = "living", chance = 1, base = 0.8, minday = 20, maxday = nil }, -- 机械战车
		{ prefab = "nightmarebeak", tag = "living", chance = 1, base = 2, minday = 15, maxday = 45 }, -- 梦魇鸟
		{ prefab = "shadow_bishop", tag = "living", chance = 1, base = 1.5, minday = 15, maxday = 45 }, -- 暗影主教
		{ prefab = "shadow_knight", tag = "living", chance = 1, base = 1.5, minday = 15, maxday = 45 }, -- 暗影骑士
		{ prefab = "shadow_rook", tag = "living", chance = 1, base = 1, minday = 20, maxday = nil }, -- 暗影战车
		{ prefab = "ghost", tag = "living", chance = 1.5, base = 3, minday = 5, maxday = 45 }, -- 鬼魂
		{ prefab = "eyeplant", tag = "living", chance = 1, base = 3, minday = 20, maxday = nil }, -- 眼树
		{ prefab = "lureplant", tag = "living", chance = 1, base = 5, minday = 10, maxday = 45 }, -- 肉球茎
		{ prefab = "rocky", tag = "living", chance = 1, base = 0.4, minday = 20, maxday = nil }, -- 岩石大龙虾
		{ prefab = "deer", tag = "living", chance = 1, base = 0.5, minday = 15, maxday = nil }, -- 无眼鹿
		{ prefab = "beeguard", tag = "living", chance = 1, base = 1, minday = 20, maxday = nil }, -- 蜜蜂守卫
		{ prefab = "mossling", tag = "living", chance = 1.5, base = 0.4, minday = 25, maxday = nil }, -- 莫斯林
		{ prefab = "spat", tag = "living", chance = 1, base = 0.4, minday = 30, maxday = nil }, -- 钢羊
		{ prefab = "spiderqueen", tag = "living", chance = 1, base = 1.2, minday = 25, maxday = nil }, -- 蜘蛛女王
		{ prefab = "warg", tag = "living", chance = 1, base = 1, minday = 30, maxday = nil }, -- 座狼
		{ prefab = "leif", tag = "living", chance = 1.5, base = 2, minday = 30, maxday = nil }, -- 树精守卫
		{ prefab = "leif_sparse", tag = "living", chance = 1.5, base = 2, minday = 30, maxday = nil }, -- 树精守卫
		{ prefab = "minotaur", tag = "living", chance = 0.8, base = 0.9, minday = 40, maxday = nil }, -- 远古守护者
		{ prefab = "moose", tag = "living", chance = 1, base = 1, minday = 35, maxday = nil }, -- 鹿角鹅
		{ prefab = "bearger", tag = "living", chance = 0.8, base = 1, minday = 40, maxday = nil }, -- 熊獾
		{ prefab = "deerclops", tag = "living", chance = 0.8, base = 1, minday = 40, maxday = nil }, -- 独眼巨鹿
		{ prefab = "beequeen", tag = "living", chance = 0.6, base = 0.8, minday = 45, maxday = nil }, -- 女王蜂
		{ prefab = "dragonfly", tag = "living", chance = 0.6, base = 0.8, minday = 45, maxday = nil }, -- 龙蝇
		{ prefab = "toadstool", tag = "living", chance = 0.5, base = 0.3, minday = 50, maxday = nil }, -- 剧毒蕈蟾
	},
	buff = {
		{ prefab = "maxhunger", chance = 0.8, base = 1, minday = 10, maxday = nil },
		{ prefab = "maxsanity", chance = 0.8, base = 1, minday = 10, maxday = nil },
		{ prefab = "maxhealth", chance = 0.8, base = 0.6, minday = 15, maxday = nil },
		{ prefab = "hunger", chance = 1.5, base = 1.5, minday = 1, maxday = nil },
		{ prefab = "sanity", chance = 1.0, base = 1.5, minday = 1, maxday = nil },
		{ prefab = "health", chance = 1.0, base = 1.2, minday = 1, maxday = nil },
		{ prefab = "forcefield", chance = 1.0, base = 2.5, minday = 1, maxday = nil },
	},
}
