return {
  ["workshop-1207269058"]={
    configuration_options={ ddon=true, hbcolor="dynamic", hblength=5, hbpos=1, hbstyle="heart" },
    enabled=true
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2
    },
    enabled=true
  },
  ["workshop-378965501"]={
    configuration_options={ MARBLESUITSPDMULT=1, PIGGYBACKSPDMULT=1 },
    enabled=true
  },
  ["workshop-441356490"]={
    configuration_options={
      AMULET_DURABILITY=2,
      ARMOR_DURABILITY=2,
      BOOK_DURABILITY=2,
      CAMPING_DURABILITY=2,
      CLOTHING_DURABILITY=2,
      DEBUGOPTIONS="Off",
      FOOD_PRESERVATION=2,
      FOOD_SELECTION="All",
      GOLD_DURABILITY=2,
      LIGHT_DURABILITY=2,
      STAFF_DURABILITY=2,
      TOOL_DURABILITY=2,
      TRAP_DURABILITY=2,
      WEAPON_DURABILITY=2
    },
    enabled=true
  },
  ["workshop-458940297"]={
    configuration_options={
      DFV_ClientPrediction="default",
      DFV_FueledSettings="default",
      DFV_Language="EN",
      DFV_MinimalMode="default",
      DFV_PercentReplace="default",
      DFV_ShowACondition="default",
      DFV_ShowADefence="default",
      DFV_ShowAType="default",
      DFV_ShowDamage="default",
      DFV_ShowFireTime="default",
      DFV_ShowInsulation="default",
      DFV_ShowTemperature="default",
      DFV_ShowUses="default"
    },
    enabled=true
  },
  ["workshop-462434129"]={
    configuration_options={
      MOD_RESTART_ALLOW_KILL=true,
      MOD_RESTART_ALLOW_RESTART=true,
      MOD_RESTART_ALLOW_RESURRECT=true,
      MOD_RESTART_CD_BONUS=0,
      MOD_RESTART_CD_KILL=0,
      MOD_RESTART_CD_MAX=0,
      MOD_RESTART_CD_RESTART=0,
      MOD_RESTART_CD_RESURRECT=0,
      MOD_RESTART_FORCE_DROP_MODE=0,
      MOD_RESTART_IGNORING_ADMIN=true,
      MOD_RESTART_MAP_SAVE=2,
      MOD_RESTART_RESURRECT_HEALTH=0,
      MOD_RESTART_TRIGGER_MODE=1,
      MOD_RESTART_WELCOME_TIPS=true,
      MOD_RESTART_WELCOME_TIPS_TIME=6
    },
    enabled=true
  },
  ["workshop-463718554"]={
    configuration_options={
      AMOUNTOFCHESTERS=8,
      BEESSPEEDMULTIPLIER=1.2,
      CANHAUNT=1,
      CAVESTARTINGITEMS=true,
      DRAGONFLYBALANCE=true,
      DRYINGSPEEDMULTIPLIER=2,
      EMPTYINVENTORYDAYS=-1,
      FARMINGSPEEDMULTIPLIER=2,
      GHOSTSANITYDRAIN=false,
      KRAMPUSMULTIPLIER=2,
      MAXMAXPLAYERS=32,
      NIGHTSTARTINGITEMS=true,
      PREVENTBURNING=0,
      PREVENTDESTROYINGDAYS=2,
      PREVENTSTEALINGDAYS=0,
      PVPSTARTINGITEMS=true,
      RENEWLIMITEDRESOURCES=18,
      RESIZEFIREPITS=true,
      REVEALMAP=1,
      REVIVERCRAFTPENALTY=false,
      SEASONSTARTINGITEMS=true,
      SPREADFIRE=2,
      STARTINGITEMS=true
    },
    enabled=true
  },
  ["workshop-501385076"]={ configuration_options={  }, enabled=true },
  ["workshop-597417408"]={
    configuration_options={
      Clean_Period="600",
      Cleaning_delay="0",
      Cleaning_text="Cleaning server...",
      Cleaning_warning_text="",
      Custom_prefabs="",
      babybeefalo_Amount="10",
      bee_Amount="0",
      beefalo_Amount="30",
      beefaloherd_Amount="10",
      carrot_planted_Amount="100",
      eat_things="yes",
      flower_Amount="100",
      killerbee_Amount="0",
      krampus_Amount="20",
      lavae_Amount="0",
      skeleton_player_Amount="100",
      slurper_Amount="0",
      spider_Amount="0",
      spider_warrior_Amount="10",
      spiderden_Amount="10",
      spoiled_food_Amount="0"
    },
    enabled=true
  },
  ["workshop-623749604"]={
    configuration_options={
      Craft="Normal",
      Destroyable="DestroyByAll",
      FoodSpoilage=1,
      Language="En",
      Position="Center",
      Slots=80
    },
    enabled=true
  },
  ["workshop-679636739"]={ configuration_options={  }, enabled=true }
}
